export const PERMISSIONS = {
    CREATE_USER: 'create:user',
    UPDATE_USER_ROLE: 'update:user-role',
    UPDATE_USER_STATUS: 'update:user-status',
    READ_ALL_USERS: 'read:all-users',
    READ_USER: 'read:user',
    DELETE_USER: 'delete:user',
    UPDATE_OWN_PROFILE: 'update:own-profile',
    UPDATE_OWN_PASSWORD: 'update:own-password',
    READ_OWN_PROFILE: 'read:own-profile',
    ACCESS_PREMIUM_FEATURES: 'access:premium-features',
    AUTH_LOGIN: 'auth:login',
    AUTH_REFRESH: 'auth:refresh',
    AUTH_LOGOUT: 'auth:logout',
    AUTH_FORGOT_PASSWORD: 'auth:forgot-password',
    AUTH_RESET_PASSWORD: 'auth:reset-password',
    MANAGE_SYSTEM_SETTINGS: 'manage:system-settings',
  };