import { PERMISSIONS } from './permissions';

export const ROLE_PERMISSIONS = {
  SuperAdmin: Object.values(PERMISSIONS), // Accès à tout
  Admin: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER_ROLE,
    PERMISSIONS.UPDATE_USER_STATUS,
    PERMISSIONS.READ_ALL_USERS,
    PERMISSIONS.READ_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.READ_ALL_ROLES,
    PERMISSIONS.READ_ROLE_PERMISSIONS,
  ],

  User: [
    PERMISSIONS.UPDATE_OWN_PROFILE,
    PERMISSIONS.UPDATE_OWN_PASSWORD,
    PERMISSIONS.READ_OWN_PROFILE,
  ],

  User2: [
    PERMISSIONS.UPDATE_OWN_PROFILE,
    PERMISSIONS.UPDATE_OWN_PASSWORD,
    PERMISSIONS.READ_OWN_PROFILE,
  ],

  User3: [
    PERMISSIONS.UPDATE_OWN_PROFILE,
    PERMISSIONS.UPDATE_OWN_PASSWORD,
    PERMISSIONS.READ_OWN_PROFILE,
    PERMISSIONS.ACCESS_PREMIUM_FEATURES,
  ],
  
  User4: [
    PERMISSIONS.UPDATE_OWN_PROFILE,
    PERMISSIONS.UPDATE_OWN_PASSWORD,
    PERMISSIONS.READ_OWN_PROFILE,
    PERMISSIONS.ACCESS_PREMIUM_FEATURES,
  ],
};